### ISSUE TITLE
Kart son kullanım tarihi formatı

### ISSUE THREAD

**Issue by hasandz** [yasinkuyu/omnipay-posnet#3]
Yapıkredi ile test yapmak istedim, fakat kartın son kullanma tarihi ters olduğundan kabul etmiyor. 'my' yerine 'ym' olarak değiştirince kabul ediyor. 

`$data['expDate'] = $this->getCard()->getExpiryDate('ym');`

https://github.com/yasinkuyu/omnipay-posnet/blob/master/src/Message/PurchaseRequest.php#L45

**Comment by hasandz** [comment]
Closed issue'lar içinde daha önce belirtilmiş, kapatıyorum bende.

**Comment by yasinkuyu** [comment]
Güncelledim. Bilgi için teşekkürler.
